FROM public.ecr.aws/lambda/python:3.12

RUN microdnf install -y gcc postgresql-devel python3-devel && \
      microdnf clean all && \
      rm -rf /var/cache/yum /var/cache/dnf /tmp/*

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install --no-cache-dir -r requirements.txt

COPY *.py ${LAMBDA_TASK_ROOT}
CMD ["lambda_function.handler"]