apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-indexing
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 1
  selector:
    matchLabels:
      app: worker-indexing
  template:
    metadata:
      labels:
        app: worker-indexing
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: worker-pool
      containers:
      - name: worker
        image: registry.digitalocean.com/horizontal/api:worker-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: QUEUE_NAMES
          value: "indexing,question,default"
        - name: QUEUE_TIMEOUT
          value: "1800"
        - name: QUEUE_TRIES
          value: "3"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-question
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 1
  selector:
    matchLabels:
      app: worker-question
  template:
    metadata:
      labels:
        app: worker-question
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: worker-pool
      containers:
      - name: worker
        image: registry.digitalocean.com/horizontal/api:worker-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: QUEUE_NAMES
          value: "question,indexing,default"
        - name: QUEUE_TIMEOUT
          value: "1800"
        - name: QUEUE_TRIES
          value: "3"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 1
  selector:
    matchLabels:
      app: worker-default
  template:
    metadata:
      labels:
        app: worker-default
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: worker-pool
      containers:
      - name: worker
        image: registry.digitalocean.com/horizontal/api:worker-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: QUEUE_NAMES
          value: "default,question,indexing"
        - name: QUEUE_TIMEOUT
          value: "1800"
        - name: QUEUE_TRIES
          value: "3"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
