apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-indexing
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: worker-indexing
  template:
    metadata:
      labels:
        app: worker-indexing
    spec:
      terminationGracePeriodSeconds: 300 # to avoid killing jobs while running
      nodeSelector:
        doks.digitalocean.com/node-pool: worker-pool
      containers:
      - name: worker
        image: registry.digitalocean.com/horizontal/api:worker-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: QUEUE_NAMES
          value: "indexing,question,default"
        - name: QUEUE_TIMEOUT
          value: "1800"
        - name: QUEUE_TRIES
          value: "1"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-question
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: worker-question
  template:
    metadata:
      labels:
        app: worker-question
    spec:
      terminationGracePeriodSeconds: 300 # to avoid killing jobs while running
      nodeSelector:
        doks.digitalocean.com/node-pool: worker-pool
      containers:
      - name: worker
        image: registry.digitalocean.com/horizontal/api:worker-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: QUEUE_NAMES
          value: "question,indexing,default"
        - name: QUEUE_TIMEOUT
          value: "1800"
        - name: QUEUE_TRIES
          value: "1"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-default
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: worker-default
  template:
    metadata:
      labels:
        app: worker-default
    spec:
      terminationGracePeriodSeconds: 300 # to avoid killing jobs while running
      nodeSelector:
        doks.digitalocean.com/node-pool: worker-pool
      containers:
      - name: worker
        image: registry.digitalocean.com/horizontal/api:worker-latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: QUEUE_NAMES
          value: "default,question,indexing"
        - name: QUEUE_TIMEOUT
          value: "1800"
        - name: QUEUE_TRIES
          value: "1"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
