services:
   redis:
     image: redis:7.4.2-alpine
     restart: always
     healthcheck:
       test: [ "CMD", "redis-cli", "--tls", "--insecure", "-a", "${REDIS_PASSWORD}", "ping" ]
       interval: 30s
       timeout: 5s
       retries: 3
       start_period: 30s
     ports:
       - "6379:6379"
     volumes:
       - ./redisdata:/data
       - ./certs:/tls:ro
     command: >
       redis-server
       --tls-port 6379
       --port 0
       --tls-cert-file /tls/redis.crt
       --tls-key-file /tls/redis.key
       --tls-auth-clients no
       --requirepass ${REDIS_PASSWORD}