name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install doctl
        run: |
          wget https://github.com/digitalocean/doctl/releases/download/v1.94.0/doctl-1.94.0-linux-amd64.tar.gz
          tar xf ./doctl-1.94.0-linux-amd64.tar.gz
          sudo mv ./doctl /usr/local/bin
          doctl version

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          chmod +x kubectl
          sudo mv ./kubectl /usr/local/bin
          kubectl version --client

      - name: Authenticate to DigitalOcean
        run: |
          doctl auth init --access-token ${{ secrets.DOCTL_TOKEN }}
          doctl k8s cluster kubeconfig save ${{ secrets.DO_CLUSTER_ID }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build Docker image
        run: |
          docker build -t registry.digitalocean.com/horizontal/api:latest --target=api -f ./api/Dockerfile.prod api

      - name: Push Docker image
        run: |
          docker push registry.digitalocean.com/horizontal/api:latest

      - name: Prepare secrets
        run: |
          cp k8s/app-secrets.yaml.template k8s/app-secrets.yaml

          sed -i "s|\$APP_KEY|$(echo -n '${{ secrets.APP_KEY }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$DB_HOST|$(echo -n '${{ secrets.DB_HOST }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$DB_PORT|$(echo -n '${{ secrets.DB_PORT }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$DB_DATABASE|$(echo -n '${{ secrets.DB_DATABASE }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$DB_USERNAME|$(echo -n '${{ secrets.DB_USERNAME }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$DB_PASSWORD|$(echo -n '${{ secrets.DB_PASSWORD }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$REDIS_HOST|$(echo -n '${{ secrets.REDIS_HOST }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$REDIS_PASSWORD|$(echo -n '${{ secrets.REDIS_PASSWORD }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$REDIS_PORT|$(echo -n '${{ secrets.REDIS_PORT }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$REDIS_URL|$(echo -n '${{ secrets.REDIS_URL }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$FIREWORKS_API_KEY|$(echo -n '${{ secrets.FIREWORKS_API_KEY }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$TOGETHER_API_KEY|$(echo -n '${{ secrets.TOGETHER_API_KEY }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$GOOGLE_CHAT_CLIENT_ID|$(echo -n '${{ secrets.GOOGLE_CHAT_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GOOGLE_CHAT_CLIENT_SECRET|$(echo -n '${{ secrets.GOOGLE_CHAT_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GOOGLE_CHAT_PROJECT_ID|$(echo -n '${{ secrets.GOOGLE_CHAT_PROJECT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$GOOGLE_DRIVE_CLIENT_ID|$(echo -n '${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GOOGLE_DRIVE_CLIENT_SECRET|$(echo -n '${{ secrets.GOOGLE_DRIVE_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GOOGLE_DRIVE_PROJECT_ID|$(echo -n '${{ secrets.GOOGLE_DRIVE_PROJECT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$GOOGLE_AUTH_CLIENT_ID|$(echo -n '${{ secrets.GOOGLE_AUTH_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GOOGLE_AUTH_CLIENT_SECRET|$(echo -n '${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$JIRA_APP_ID|$(echo -n '${{ secrets.JIRA_APP_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$JIRA_CLIENT_ID|$(echo -n '${{ secrets.JIRA_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$JIRA_CLIENT_SECRET|$(echo -n '${{ secrets.JIRA_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$SLACK_APP_ID|$(echo -n '${{ secrets.SLACK_APP_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$SLACK_CLIENT_ID|$(echo -n '${{ secrets.SLACK_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$SLACK_CLIENT_SECRET|$(echo -n '${{ secrets.SLACK_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$LINEAR_CLIENT_ID|$(echo -n '${{ secrets.LINEAR_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$LINEAR_CLIENT_SECRET|$(echo -n '${{ secrets.LINEAR_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$GITHUB_APP_ID|$(echo -n '${{ secrets.GH_APP_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GITHUB_CLIENT_ID|$(echo -n '${{ secrets.GH_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GITHUB_CLIENT_SECRET|$(echo -n '${{ secrets.GH_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GITHUB_PRIVATE_KEY|$(echo -n '${{ secrets.GH_PRIVATE_KEY }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          sed -i "s|\$GITHUB_AUTH_APP_ID|$(echo -n '${{ secrets.GH_AUTH_APP_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GITHUB_AUTH_CLIENT_ID|$(echo -n '${{ secrets.GH_AUTH_CLIENT_ID }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GITHUB_AUTH_CLIENT_SECRET|$(echo -n '${{ secrets.GH_AUTH_CLIENT_SECRET }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml
          sed -i "s|\$GITHUB_AUTH_PRIVATE_KEY|$(echo -n '${{ secrets.GH_AUTH_PRIVATE_KEY }}' | base64 | tr -d '\n')|" k8s/app-secrets.yaml

          cat k8s/app-secrets.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/app-secrets.yaml
          kubectl apply -f k8s/app-config.yaml
          kubectl apply -f k8s/api-deployment.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/api
          kubectl get pods -l app=api
